import type { SalesOrder } from "../shared/types";

export const emptySalesOrder = (): SalesOrder => ({
  id: "",
  soNo: "",
  quotationId: "",
  leadId: "",
  customerName: "",
  mobile: "",
  email: "",
  address: "",
  city: "",
  model: "",
  remark: "",
  qty: 1,
  unitPrice: 0,
  totalAmount: 0,
  mode: "asIs",
  aadharNumber: "",
  aadharImage: "",
  panNumber: "",
  panImage: "",
  gstNumber: "",
  gstImage: "",
});