import {
  Category,
  Employee,
  EnquirySource,
  EnquiryStatus,
  Finance,
  ItemMaster,
  Model,
  ProductSeries,
  Profession,
  Variant,
  VariantStructure,
  Account,
} from "./types";
import { buildVariantStructureFromVariant } from "./variantStructureUtils";

export const SEED_CATEGORIES: Category[] = [
  { id: "cat-1", code: "CAT001", categoryName: "Commercial Vehicles", slug: "commercial-vehicles", createdAt: "2024-01-10T00:00:00.000Z", status: "active" },
  { id: "cat-2", code: "CAT002", categoryName: "Passenger Vehicles", slug: "passenger-vehicles", createdAt: "2024-01-11T00:00:00.000Z", status: "active" },
  { id: "cat-3", code: "CAT003", categoryName: "Agricultural Equipment", slug: "agricultural-equipment", createdAt: "2024-01-12T00:00:00.000Z", status: "active" },
  { id: "cat-4", code: "CAT004", categoryName: "Spare Parts", slug: "spare-parts", createdAt: "2024-01-13T00:00:00.000Z", status: "inactive" },
  { id: "cat-5", code: "CAT005", categoryName: "Electric Vehicles", slug: "electric-vehicles", createdAt: "2024-01-14T00:00:00.000Z", status: "active" },
];
export const SEED_PRODUCT_SERIES: ProductSeries[] = [
  { id: "ser-1", categoryId: "cat-1", seriesCode: "PS001", seriesName: "Pro Haul", capacity: "16 Ton", status: "active" },
  { id: "ser-2", categoryId: "cat-1", seriesCode: "PS002", seriesName: "City Cargo", capacity: "9 Ton", status: "active" },
  { id: "ser-3", categoryId: "cat-2", seriesCode: "PS003", seriesName: "Urban Comfort", capacity: "7 Seater", status: "active" },
  { id: "ser-4", categoryId: "cat-3", seriesCode: "PS004", seriesName: "Farm King", capacity: "45 HP", status: "active" },
  { id: "ser-5", categoryId: "cat-5", seriesCode: "PS005", seriesName: "E-Drive", capacity: "12 Ton", status: "active" },
];
export const SEED_ENQUIRY_SOURCES: EnquirySource[] = [
  { id: "src-1", code: "SRC001", sourceName: "Walk In",       slug: "walk-in",        createdAt: "2024-01-10T00:00:00.000Z", status: "active" },
  { id: "src-2", code: "SRC002", sourceName: "Phone Call",    slug: "phone-call",     createdAt: "2024-01-11T00:00:00.000Z", status: "active" },
  { id: "src-3", code: "SRC003", sourceName: "Online Portal", slug: "online-portal",  createdAt: "2024-01-12T00:00:00.000Z", status: "active" },
  { id: "src-4", code: "SRC004", sourceName: "Referral",      slug: "referral",       createdAt: "2024-01-13T00:00:00.000Z", status: "active" },
  { id: "src-5", code: "SRC005", sourceName: "Exhibition",    slug: "exhibition",     createdAt: "2024-01-14T00:00:00.000Z", status: "inactive" },
];
export const SEED_PROFESSIONS: Profession[] = [
  { id: "pro-1", code: "PRO001", professionName: "Business Owner",  slug: "business-owner",  createdAt: "2024-01-10T00:00:00.000Z", status: "active" },
  { id: "pro-2", code: "PRO002", professionName: "Salaried",        slug: "salaried",        createdAt: "2024-01-11T00:00:00.000Z", status: "active" },
  { id: "pro-3", code: "PRO003", professionName: "Self Employed",   slug: "self-employed",   createdAt: "2024-01-12T00:00:00.000Z", status: "active" },
  { id: "pro-4", code: "PRO004", professionName: "Farmer",          slug: "farmer",          createdAt: "2024-01-13T00:00:00.000Z", status: "active" },
  { id: "pro-5", code: "PRO005", professionName: "Contractor",      slug: "contractor",      createdAt: "2024-01-14T00:00:00.000Z", status: "inactive" },
];
export const SEED_ENQUIRY_STATUSES: EnquiryStatus[] = [
  { id: "est-1", code: "EST001", statusName: "New",         slug: "new",         createdAt: "2024-01-10T00:00:00.000Z", status: "active" },
  { id: "est-2", code: "EST002", statusName: "Follow Up",   slug: "follow-up",   createdAt: "2024-01-11T00:00:00.000Z", status: "active" },
  { id: "est-3", code: "EST003", statusName: "Interested",  slug: "interested",  createdAt: "2024-01-12T00:00:00.000Z", status: "active" },
  { id: "est-4", code: "EST004", statusName: "Converted",   slug: "converted",   createdAt: "2024-01-13T00:00:00.000Z", status: "active" },
  { id: "est-5", code: "EST005", statusName: "Lost",        slug: "lost",        createdAt: "2024-01-14T00:00:00.000Z", status: "inactive" },
];
export const SEED_EMPLOYEES: Employee[] = [
  { id: "emp-1", typeOfDepartment: "sale", branch: "main-branch", role: "sale-manager", employeeName: "Rajesh Patel", mobileNumber: "9876543210", alternateNumber: "9876500000", email: "rajesh.patel@autobook.com", password: "", createdBy: "Admin", createdType: "Manual", createdAt: "2024-01-10T00:00:00.000Z" },
  { id: "emp-2", typeOfDepartment: "sale", branch: "main-branch", role: "sale-executive", employeeName: "Priya Shah", mobileNumber: "9876543211", alternateNumber: "", email: "priya.shah@autobook.com", password: "", createdBy: "Admin", createdType: "Manual", createdAt: "2024-01-11T00:00:00.000Z" },
  { id: "emp-3", typeOfDepartment: "sale", branch: "main-branch", role: "accountant", employeeName: "Kiran Mehta", mobileNumber: "9876543212", alternateNumber: "", email: "kiran.mehta@autobook.com", password: "", createdBy: "Admin", createdType: "Manual", createdAt: "2024-01-12T00:00:00.000Z" },
  { id: "emp-4", typeOfDepartment: "production", branch: "main-branch", role: "welding", employeeName: "Suresh Kumar", mobileNumber: "9876543213", alternateNumber: "", email: "suresh.kumar@autobook.com", password: "", createdBy: "Admin", createdType: "Manual", createdAt: "2024-01-13T00:00:00.000Z" },
  { id: "emp-5", typeOfDepartment: "production", branch: "main-branch", role: "production-manager", employeeName: "Vikram Desai", mobileNumber: "9876543214", alternateNumber: "", email: "vikram.desai@autobook.com", password: "", createdBy: "Admin", createdType: "Manual", createdAt: "2024-01-14T00:00:00.000Z" },
];
export const SEED_FINANCES: Finance[] = [
  { id: "fin-1", financeName: "Bajaj Finance",   slug: "bajaj-finance",   createdAt: "2024-01-10T00:00:00.000Z", status: "active" },
  { id: "fin-2", financeName: "Tata Capital",    slug: "tata-capital",    createdAt: "2024-01-11T00:00:00.000Z", status: "active" },
  { id: "fin-3", financeName: "Mahindra Finance",slug: "mahindra-finance", createdAt: "2024-01-12T00:00:00.000Z", status: "active" },
  { id: "fin-4", financeName: "HDB Financial",   slug: "hdb-financial",   createdAt: "2024-01-13T00:00:00.000Z", status: "active" },
  { id: "fin-5", financeName: "Shriram Finance", slug: "shriram-finance", createdAt: "2024-01-14T00:00:00.000Z", status: "inactive" },
];
export const SEED_MODELS: Model[] = [
  {
    id: "mod-1",
    categoryId: "cat-1",
    seriesId: "ser-1",
    modelCode: "MD001",
    modelName: "Pro Haul 1616",
    axleType: "6x2",
    capacity: "16 Ton",
    length: "32 ft",
    width: "8.2 ft",
    height: "9.5 ft",
    standardWeight: "8500 kg",
    status: "active",
  },
  {
    id: "mod-2",
    categoryId: "cat-1",
    seriesId: "ser-1",
    modelCode: "MD002",
    modelName: "Pro Haul 1414",
    axleType: "4x2",
    capacity: "14 Ton",
    length: "28 ft",
    width: "8 ft",
    height: "9 ft",
    standardWeight: "7200 kg",
    status: "active",
  },
  {
    id: "mod-3",
    categoryId: "cat-1",
    seriesId: "ser-2",
    modelCode: "MD003",
    modelName: "City Cargo 909",
    axleType: "4x2",
    capacity: "9 Ton",
    length: "22 ft",
    width: "7.5 ft",
    height: "8.5 ft",
    standardWeight: "5500 kg",
    status: "active",
  },
  {
    id: "mod-4",
    categoryId: "cat-2",
    seriesId: "ser-3",
    modelCode: "MD004",
    modelName: "Urban Comfort 7S",
    axleType: "4x2",
    capacity: "7 Seater",
    length: "18 ft",
    width: "6.8 ft",
    height: "7.2 ft",
    standardWeight: "2100 kg",
    status: "active",
  },
  {
    id: "mod-5",
    categoryId: "cat-5",
    seriesId: "ser-5",
    modelCode: "MD005",
    modelName: "E-Drive 1212",
    axleType: "6x4",
    capacity: "12 Ton",
    length: "30 ft",
    width: "8 ft",
    height: "9 ft",
    standardWeight: "6800 kg",
    status: "inactive",
  },
  {
    id: "mod-6",
    categoryId: "cat-3",
    seriesId: "ser-4",
    modelCode: "MD006",
    modelName: "Farm King 4545",
    axleType: "4x4",
    capacity: "45 HP",
    length: "16 ft",
    width: "6.5 ft",
    height: "7 ft",
    standardWeight: "2800 kg",
    status: "active",
  },
];

export const SEED_VARIANTS: Variant[] = [
  {
    id: "var-1",
    categoryId: "cat-1",
    seriesId: "ser-1",
    modelId: "mod-1",
    variantCode: "VR001",
    variantName: "Pro Haul Tipper",
    bodyType: "tipper",
    axleBrand: "tata",
    hydraulicBrand: "hyva",
    tyreBrand: "mrf",
    targetCost: "1250000",
    sellingPrice: "1480000",
  },
  {
    id: "var-2",
    categoryId: "cat-1",
    seriesId: "ser-1",
    modelId: "mod-1",
    variantCode: "VR002",
    variantName: "Pro Haul Container",
    bodyType: "closed",
    axleBrand: "ashok",
    hydraulicBrand: "wabco",
    tyreBrand: "ceat",
    targetCost: "1180000",
    sellingPrice: "1390000",
  },
  {
    id: "var-3",
    categoryId: "cat-1",
    seriesId: "ser-2",
    modelId: "mod-3",
    variantCode: "VR003",
    variantName: "City Cargo Open",
    bodyType: "open",
    axleBrand: "eicher",
    hydraulicBrand: "parker",
    tyreBrand: "apollo",
    targetCost: "780000",
    sellingPrice: "920000",
  },
  {
    id: "var-4",
    categoryId: "cat-2",
    seriesId: "ser-3",
    modelId: "mod-4",
    variantCode: "VR004",
    variantName: "Urban Comfort Deluxe",
    bodyType: "closed",
    axleBrand: "bharatbenz",
    hydraulicBrand: "hyva",
    tyreBrand: "jk",
    targetCost: "950000",
    sellingPrice: "1120000",
  },
  {
    id: "var-5",
    categoryId: "cat-5",
    seriesId: "ser-5",
    modelId: "mod-5",
    variantCode: "VR005",
    variantName: "E-Drive Tanker",
    bodyType: "tanker",
    axleBrand: "tata",
    hydraulicBrand: "wabco",
    tyreBrand: "mrf",
    targetCost: "1650000",
    sellingPrice: "1890000",
  },
  {
    id: "var-6",
    categoryId: "cat-1",
    seriesId: "ser-1",
    modelId: "mod-2",
    variantCode: "VR006",
    variantName: "Pro Haul 1414 Flatbed",
    bodyType: "flatbed",
    axleBrand: "tata",
    hydraulicBrand: "hyva",
    tyreBrand: "bridgestone",
    targetCost: "1050000",
    sellingPrice: "1240000",
  },
  {
    id: "var-7",
    categoryId: "cat-1",
    seriesId: "ser-1",
    modelId: "mod-2",
    variantCode: "VR007",
    variantName: "Pro Haul 1414 Reefer",
    bodyType: "reefer",
    axleBrand: "volvo",
    hydraulicBrand: "danfoss",
    tyreBrand: "goodyear",
    targetCost: "1320000",
    sellingPrice: "1550000",
  },
  {
    id: "var-8",
    categoryId: "cat-1",
    seriesId: "ser-2",
    modelId: "mod-3",
    variantCode: "VR008",
    variantName: "City Cargo Closed Van",
    bodyType: "closed",
    axleBrand: "eicher",
    hydraulicBrand: "bosch",
    tyreBrand: "ceat",
    targetCost: "820000",
    sellingPrice: "965000",
  },
  {
    id: "var-9",
    categoryId: "cat-2",
    seriesId: "ser-3",
    modelId: "mod-4",
    variantCode: "VR009",
    variantName: "Urban Comfort Standard",
    bodyType: "closed",
    axleBrand: "ashok",
    hydraulicBrand: "parker",
    tyreBrand: "apollo",
    targetCost: "880000",
    sellingPrice: "1040000",
  },
  {
    id: "var-10",
    categoryId: "cat-3",
    seriesId: "ser-4",
    modelId: "mod-6",
    variantCode: "VR010",
    variantName: "Farm King Trailer",
    bodyType: "open",
    axleBrand: "man",
    hydraulicBrand: "hyva",
    tyreBrand: "jk",
    targetCost: "420000",
    sellingPrice: "495000",
  },
  {
    id: "var-11",
    categoryId: "cat-1",
    seriesId: "ser-1",
    modelId: "mod-1",
    variantCode: "VR011",
    variantName: "Pro Haul Tipper Premium",
    bodyType: "tipper",
    axleBrand: "bharatbenz",
    hydraulicBrand: "wabco",
    tyreBrand: "mrf",
    targetCost: "1380000",
    sellingPrice: "1620000",
  },
  {
    id: "var-12",
    categoryId: "cat-5",
    seriesId: "ser-5",
    modelId: "mod-5",
    variantCode: "VR012",
    variantName: "E-Drive Container",
    bodyType: "closed",
    axleBrand: "tata",
    hydraulicBrand: "danfoss",
    tyreBrand: "bridgestone",
    targetCost: "1580000",
    sellingPrice: "1820000",
  },
];

export const SEED_ITEMS: ItemMaster[] = [
  {
    id: "item-1",
    itemCode: "ITM001",
    itemName: "Hydraulic Cylinder Assembly",
    shortName: "Hyd Cyl Assy",
    itemCategory: "spare",
    group: "group-a",
    unit: "pcs",
    taxSlab: "18",
    stockMapping: true,
    minQty: "10",
    maxQty: "200",
    itemType: "sub-assembly",
    suppliers: ["supplier-1", "supplier-2"],
    purchasePrice: "12500",
    actualPurchasePrice: "11800",
    salesPrice: "15200",
    mrp: "16500",
    barcode: "8901234567001",
  },
  {
    id: "item-2",
    itemCode: "ITM002",
    itemName: "Engine Oil Filter",
    shortName: "Oil Filter",
    itemCategory: "consumable",
    group: "group-b",
    unit: "pcs",
    taxSlab: "12",
    stockMapping: true,
    minQty: "50",
    maxQty: "500",
    itemType: "consumable",
    suppliers: ["supplier-2", "supplier-3"],
    purchasePrice: "450",
    actualPurchasePrice: "420",
    salesPrice: "580",
    mrp: "650",
    barcode: "8901234567002",
  },
  {
    id: "item-3",
    itemCode: "ITM003",
    itemName: "Mild Steel Sheet 4mm",
    shortName: "MS Sheet 4mm",
    itemCategory: "raw",
    group: "group-a",
    unit: "kg",
    taxSlab: "18",
    stockMapping: true,
    minQty: "500",
    maxQty: "5000",
    itemType: "raw-material",
    suppliers: ["supplier-1", "supplier-4"],
    purchasePrice: "68",
    actualPurchasePrice: "65",
    salesPrice: "82",
    mrp: "90",
    barcode: "8901234567003",
  },
  {
    id: "item-4",
    itemCode: "ITM004",
    itemName: "Finished Tipper Body",
    shortName: "Tipper Body",
    itemCategory: "finished",
    group: "group-c",
    unit: "set",
    taxSlab: "28",
    stockMapping: false,
    minQty: "2",
    maxQty: "20",
    itemType: "finished-goods",
    suppliers: ["supplier-3"],
    purchasePrice: "285000",
    actualPurchasePrice: "275000",
    salesPrice: "320000",
    mrp: "345000",
    barcode: "8901234567004",
  },
  {
    id: "item-5",
    itemCode: "ITM005",
    itemName: "Workshop Service Labour",
    shortName: "WS Labour",
    itemCategory: "consumable",
    group: "group-b",
    unit: "pcs",
    taxSlab: "5",
    stockMapping: false,
    minQty: "0",
    maxQty: "0",
    itemType: "service",
    suppliers: ["supplier-4"],
    purchasePrice: "800",
    actualPurchasePrice: "800",
    salesPrice: "1200",
    mrp: "1200",
    barcode: "8901234567005",
  },
  {
    id: "item-6",
    itemCode: "ITM006",
    itemName: "Welding Machine 200A",
    shortName: "Weld Machine",
    itemCategory: "spare",
    group: "group-c",
    unit: "pcs",
    taxSlab: "18",
    stockMapping: true,
    minQty: "3",
    maxQty: "15",
    itemType: "tool-equipment",
    suppliers: ["supplier-2", "supplier-5"],
    purchasePrice: "18500",
    actualPurchasePrice: "17800",
    salesPrice: "22500",
    mrp: "24000",
    barcode: "8901234567006",
  },
];

export const SEED_ACCOUNTS: Account[] = [
  {
    id: "acc-1",
    accountName: "Denish Patel",
    printName: "Denish Patel",
    openingBalance: "0.00",
    drOrCr: "DR",

    groupId: "30",

    countryName: "India",
    stateName: "Maharashtra",
    stateCode: "24",
    districtName: "",
    talukaName: "Aheri",
    cityName: "",
    area: "Jalgaon",

    addressLine1: "123, Main Street",
    addressLine2: "Near Bus Stand",
    pincode: "",

    phoneNo: "9081540774",
    mobileNo: "9081540774",
    email: "denish.patel@example.com",
    contactPersonName: "Denish Patel",

    birthdayOn: "",
    anniversary: "",

    bankAccountNo: "",
    bankName: "",
    ifscCode: "SBIN0001234",
    branchName: "Main Branch",

    gstNo: "27AABCU1234D1Z1",
    panCard: "AABCU1234D",
    aadharCardNo: "",

    createdAt: new Date().toISOString(),
    status: "active",
  }
];

export const SEED_VARIANT_STRUCTURES: VariantStructure[] = SEED_VARIANTS.map(
  (variant, index) =>
    buildVariantStructureFromVariant(
      variant,
      SEED_CATEGORIES,
      SEED_PRODUCT_SERIES,
      SEED_MODELS,
      `vstr-${index + 1}`,
    ),
);